import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import TopHeader from "./components/top_header";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ExtremeFooter from "./components/extreme_footer";
config.autoAddCss = false;
import Image from "next/image";
import sponserImage from "@/app/assets/sponserimage.png";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const josefinSans = localFont({
  src: "./fonts/JosefinSans-Bold.ttf",
  variable: "--font-josefin-sans",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${josefinSans.variable} antialiased`}
      >
        {/* Top Header */}
        <TopHeader />

        {/* Navbar */}
        <Navbar />
        {children}
        <div className="w-auto justify-center items-center mx-8">

          <Image className=""
            src={sponserImage}
            alt="sponser image"
            width={1000}
          />
        </div>
        <Footer />
        <ExtremeFooter />
      </body>
    </html>
  );
}
